#!/usr/bin/env python3
"""Train Layer 2: Laser RX detection in cropped ROI images.

Uses the annotated Layer 2 dataset generated by generate_layer2_crops.py
and annotated by annotate_laser_rx.py.

Recommended: single-class training (laser_rx only).
  - class 0: laser_rx (target — 72mm×50mm, φ42mm detection area)
  - Light strips are rejected by classical CV post-filter (HSV color + contour
    shape analysis), no annotation data needed.

Optional: dual-class training if light_strip annotations are available.
  - class 1: light_strip (distractor — same-color LED strips on drone)
  - Classical CV filter still active as additional defense layer.

Small input size (192×192) and lightweight model for fast inference.
"""

import argparse
import os
import sys
from pathlib import Path

# detect/ directory (parent of scripts/)
DETECT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def verify_dataset(data_path):
    """Check that the Layer 2 dataset has annotated images."""
    import yaml
    with open(data_path) as f:
        cfg = yaml.safe_load(f)

    base = Path(cfg.get("path", "."))
    train_imgs = base / cfg.get("train", "images/train")
    train_labels = base / "labels" / "train"

    if not train_imgs.exists():
        print(f"ERROR: Training images directory not found: {train_imgs}")
        print("Run generate_layer2_crops.py first.")
        return False

    img_count = sum(1 for f in train_imgs.iterdir()
                    if f.suffix.lower() in {".jpg", ".jpeg", ".png"})
    if img_count == 0:
        print(f"ERROR: No images in {train_imgs}")
        print("Run generate_layer2_crops.py first.")
        return False

    annotated = 0
    if train_labels.exists():
        for lf in train_labels.iterdir():
            if lf.suffix == ".txt" and lf.stat().st_size > 0:
                annotated += 1

    print(f"Dataset: {img_count} images, {annotated} annotated")
    if annotated < 10:
        print("WARNING: Very few annotations. Consider annotating more images.")
        print(f"  python3 scripts/annotate_laser_rx.py "
              f"--images {train_imgs} --labels {train_labels}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Train Layer 2 laser_rx detector")
    parser.add_argument("--data", default=os.path.join(DETECT_DIR, "laser_rx/dataset.yaml"),
                        help="Dataset YAML path")
    parser.add_argument("--model", default="yolov8n.pt",
                        help="Base model (yolov8n/s/m)")
    parser.add_argument("--epochs", type=int, default=150)
    parser.add_argument("--imgsz", type=int, default=192,
                        help="Training image size (small for ROI crops)")
    parser.add_argument("--batch", type=int, default=64,
                        help="Batch size (can be large for small images)")
    parser.add_argument("--device", default="0")
    parser.add_argument("--project", default=os.path.join(DETECT_DIR, "model/layer2"),
                        help="Output directory")
    parser.add_argument("--name", default="train")
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()

    try:
        from ultralytics import YOLO
    except ImportError:
        print("ERROR: ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)

    data_path = os.path.abspath(args.data)
    if not os.path.isfile(data_path):
        print(f"ERROR: Dataset config not found: {data_path}")
        sys.exit(1)

    if not verify_dataset(data_path):
        sys.exit(1)

    model = YOLO(args.model)

    results = model.train(
        data=data_path,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        project=os.path.abspath(args.project),
        name=args.name,
        exist_ok=True,
        resume=args.resume,
        workers=8,
        patience=30,
        save=True,
        save_period=10,
        val=True,
        plots=True,
        # Augmentation for multi-class detection (shape + color)
        # Moderate hue variation for color robustness while preserving color distinction
        hsv_h=0.2,      # moderate hue variation (color-robust but still color-sensitive)
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=15.0,      # more rotation (module can be tilted)
        translate=0.15,
        scale=0.4,
        flipud=0.0,         # no vertical flip (module has orientation)
        fliplr=0.5,
        mosaic=0.8,
        mixup=0.0,
    )

    print("\n=== Layer 2 Training Complete ===")
    print(f"Best model: {os.path.abspath(args.project)}/{args.name}/weights/best.pt")


if __name__ == "__main__":
    main()
